name: Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run once a week at midnight on Sunday

jobs:
  security:
    runs-on: ubuntu-latest
    name: CodeQL Analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: php

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
